[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"


[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/genproto"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "golang.org/x/text"
  version = "v0.3.0"

[prune]
  go-tests = true
  unused-packages = true
