// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bank.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	proto/bank.proto

It has these top-level messages:
	Client
	Account
	Transaction
	RequestById
	RequestAccount
	RequestClient
	RequestAccountMoney
	RequestTransferMoney
	ResponseAccount
	ResponseClient
	ResponseMoney
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Client struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone string `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
}

func (m *Client) Reset()                    { *m = Client{} }
func (m *Client) String() string            { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()               {}
func (*Client) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Client) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Client) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Client) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Client) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Account struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// @inject_tag: db:"client_id"
	ClientId int32 `protobuf:"varint,2,opt,name=client_id,json=clientId" json:"client_id,omitempty" db:"client_id"`
	Balance  int64 `protobuf:"varint,3,opt,name=balance" json:"balance,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Account) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type Transaction struct {
	Id        int32           `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DiffMoney map[int32]int64 `protobuf:"bytes,2,rep,name=diff_money,json=diffMoney" json:"diff_money,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Comment   string          `protobuf:"bytes,3,opt,name=comment" json:"comment,omitempty"`
	Success   bool            `protobuf:"varint,4,opt,name=success" json:"success,omitempty"`
	Timestamp int64           `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transaction) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetDiffMoney() map[int32]int64 {
	if m != nil {
		return m.DiffMoney
	}
	return nil
}

func (m *Transaction) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Transaction) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type RequestById struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *RequestById) Reset()                    { *m = RequestById{} }
func (m *RequestById) String() string            { return proto.CompactTextString(m) }
func (*RequestById) ProtoMessage()               {}
func (*RequestById) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestById) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RequestAccount struct {
	Req *Account `protobuf:"bytes,1,opt,name=req" json:"req,omitempty"`
	Id  int32    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *RequestAccount) Reset()                    { *m = RequestAccount{} }
func (m *RequestAccount) String() string            { return proto.CompactTextString(m) }
func (*RequestAccount) ProtoMessage()               {}
func (*RequestAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestAccount) GetReq() *Account {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *RequestAccount) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RequestClient struct {
	Req *Client `protobuf:"bytes,1,opt,name=req" json:"req,omitempty"`
}

func (m *RequestClient) Reset()                    { *m = RequestClient{} }
func (m *RequestClient) String() string            { return proto.CompactTextString(m) }
func (*RequestClient) ProtoMessage()               {}
func (*RequestClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RequestClient) GetReq() *Client {
	if m != nil {
		return m.Req
	}
	return nil
}

type RequestAccountMoney struct {
	Account *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Money   int64    `protobuf:"varint,2,opt,name=money" json:"money,omitempty"`
}

func (m *RequestAccountMoney) Reset()                    { *m = RequestAccountMoney{} }
func (m *RequestAccountMoney) String() string            { return proto.CompactTextString(m) }
func (*RequestAccountMoney) ProtoMessage()               {}
func (*RequestAccountMoney) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RequestAccountMoney) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *RequestAccountMoney) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type RequestTransferMoney struct {
	Src   *Account `protobuf:"bytes,1,opt,name=src" json:"src,omitempty"`
	Dst   *Account `protobuf:"bytes,2,opt,name=dst" json:"dst,omitempty"`
	Money int64    `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
}

func (m *RequestTransferMoney) Reset()                    { *m = RequestTransferMoney{} }
func (m *RequestTransferMoney) String() string            { return proto.CompactTextString(m) }
func (*RequestTransferMoney) ProtoMessage()               {}
func (*RequestTransferMoney) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestTransferMoney) GetSrc() *Account {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *RequestTransferMoney) GetDst() *Account {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *RequestTransferMoney) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type ResponseAccount struct {
	Result []*Account `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *ResponseAccount) Reset()                    { *m = ResponseAccount{} }
func (m *ResponseAccount) String() string            { return proto.CompactTextString(m) }
func (*ResponseAccount) ProtoMessage()               {}
func (*ResponseAccount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ResponseAccount) GetResult() []*Account {
	if m != nil {
		return m.Result
	}
	return nil
}

type ResponseClient struct {
	Result []*Client `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *ResponseClient) Reset()                    { *m = ResponseClient{} }
func (m *ResponseClient) String() string            { return proto.CompactTextString(m) }
func (*ResponseClient) ProtoMessage()               {}
func (*ResponseClient) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResponseClient) GetResult() []*Client {
	if m != nil {
		return m.Result
	}
	return nil
}

type ResponseMoney struct {
	Money int64 `protobuf:"varint,1,opt,name=money" json:"money,omitempty"`
}

func (m *ResponseMoney) Reset()                    { *m = ResponseMoney{} }
func (m *ResponseMoney) String() string            { return proto.CompactTextString(m) }
func (*ResponseMoney) ProtoMessage()               {}
func (*ResponseMoney) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ResponseMoney) GetMoney() int64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func init() {
	proto.RegisterType((*Client)(nil), "api.Client")
	proto.RegisterType((*Account)(nil), "api.Account")
	proto.RegisterType((*Transaction)(nil), "api.Transaction")
	proto.RegisterType((*RequestById)(nil), "api.RequestById")
	proto.RegisterType((*RequestAccount)(nil), "api.RequestAccount")
	proto.RegisterType((*RequestClient)(nil), "api.RequestClient")
	proto.RegisterType((*RequestAccountMoney)(nil), "api.RequestAccountMoney")
	proto.RegisterType((*RequestTransferMoney)(nil), "api.RequestTransferMoney")
	proto.RegisterType((*ResponseAccount)(nil), "api.ResponseAccount")
	proto.RegisterType((*ResponseClient)(nil), "api.ResponseClient")
	proto.RegisterType((*ResponseMoney)(nil), "api.ResponseMoney")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BankService service

type BankServiceClient interface {
	ListClients(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseClient, error)
	ReadClient(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseClient, error)
	ListAccountsByClient(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error)
	CreateClient(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClient, error)
	DeleteClient(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseClient, error)
	ListAccounts(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error)
	ReadAccount(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error)
	CreateAccount(ctx context.Context, in *RequestAccount, opts ...grpc.CallOption) (*ResponseAccount, error)
	UpdateAccount(ctx context.Context, in *RequestAccount, opts ...grpc.CallOption) (*ResponseAccount, error)
	DeleteAccount(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error)
	ChangeBalance(ctx context.Context, in *RequestAccountMoney, opts ...grpc.CallOption) (*ResponseAccount, error)
	GetBalance(ctx context.Context, in *RequestAccount, opts ...grpc.CallOption) (*ResponseMoney, error)
	TransferMoney(ctx context.Context, in *RequestTransferMoney, opts ...grpc.CallOption) (*ResponseAccount, error)
}

type bankServiceClient struct {
	cc *grpc.ClientConn
}

func NewBankServiceClient(cc *grpc.ClientConn) BankServiceClient {
	return &bankServiceClient{cc}
}

func (c *bankServiceClient) ListClients(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseClient, error) {
	out := new(ResponseClient)
	err := grpc.Invoke(ctx, "/api.BankService/ListClients", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ReadClient(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseClient, error) {
	out := new(ResponseClient)
	err := grpc.Invoke(ctx, "/api.BankService/ReadClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAccountsByClient(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/ListAccountsByClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) CreateClient(ctx context.Context, in *RequestClient, opts ...grpc.CallOption) (*ResponseClient, error) {
	out := new(ResponseClient)
	err := grpc.Invoke(ctx, "/api.BankService/CreateClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) DeleteClient(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseClient, error) {
	out := new(ResponseClient)
	err := grpc.Invoke(ctx, "/api.BankService/DeleteClient", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ListAccounts(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/ListAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ReadAccount(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/ReadAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) CreateAccount(ctx context.Context, in *RequestAccount, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) UpdateAccount(ctx context.Context, in *RequestAccount, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/UpdateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) DeleteAccount(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/DeleteAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) ChangeBalance(ctx context.Context, in *RequestAccountMoney, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/ChangeBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) GetBalance(ctx context.Context, in *RequestAccount, opts ...grpc.CallOption) (*ResponseMoney, error) {
	out := new(ResponseMoney)
	err := grpc.Invoke(ctx, "/api.BankService/GetBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) TransferMoney(ctx context.Context, in *RequestTransferMoney, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := grpc.Invoke(ctx, "/api.BankService/TransferMoney", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BankService service

type BankServiceServer interface {
	ListClients(context.Context, *RequestById) (*ResponseClient, error)
	ReadClient(context.Context, *RequestById) (*ResponseClient, error)
	ListAccountsByClient(context.Context, *RequestById) (*ResponseAccount, error)
	CreateClient(context.Context, *RequestClient) (*ResponseClient, error)
	DeleteClient(context.Context, *RequestById) (*ResponseClient, error)
	ListAccounts(context.Context, *RequestById) (*ResponseAccount, error)
	ReadAccount(context.Context, *RequestById) (*ResponseAccount, error)
	CreateAccount(context.Context, *RequestAccount) (*ResponseAccount, error)
	UpdateAccount(context.Context, *RequestAccount) (*ResponseAccount, error)
	DeleteAccount(context.Context, *RequestById) (*ResponseAccount, error)
	ChangeBalance(context.Context, *RequestAccountMoney) (*ResponseAccount, error)
	GetBalance(context.Context, *RequestAccount) (*ResponseMoney, error)
	TransferMoney(context.Context, *RequestTransferMoney) (*ResponseAccount, error)
}

func RegisterBankServiceServer(s *grpc.Server, srv BankServiceServer) {
	s.RegisterService(&_BankService_serviceDesc, srv)
}

func _BankService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/ListClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListClients(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ReadClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ReadClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/ReadClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ReadClient(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAccountsByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAccountsByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/ListAccountsByClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAccountsByClient(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestClient)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CreateClient(ctx, req.(*RequestClient))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).DeleteClient(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ListAccounts(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ReadAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ReadAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/ReadAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ReadAccount(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CreateAccount(ctx, req.(*RequestAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).UpdateAccount(ctx, req.(*RequestAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).DeleteAccount(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_ChangeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccountMoney)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).ChangeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/ChangeBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).ChangeBalance(ctx, req.(*RequestAccountMoney))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).GetBalance(ctx, req.(*RequestAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_TransferMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTransferMoney)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).TransferMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.BankService/TransferMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).TransferMoney(ctx, req.(*RequestTransferMoney))
	}
	return interceptor(ctx, in, info, handler)
}

var _BankService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BankService",
	HandlerType: (*BankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListClients",
			Handler:    _BankService_ListClients_Handler,
		},
		{
			MethodName: "ReadClient",
			Handler:    _BankService_ReadClient_Handler,
		},
		{
			MethodName: "ListAccountsByClient",
			Handler:    _BankService_ListAccountsByClient_Handler,
		},
		{
			MethodName: "CreateClient",
			Handler:    _BankService_CreateClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _BankService_DeleteClient_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _BankService_ListAccounts_Handler,
		},
		{
			MethodName: "ReadAccount",
			Handler:    _BankService_ReadAccount_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _BankService_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _BankService_UpdateAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _BankService_DeleteAccount_Handler,
		},
		{
			MethodName: "ChangeBalance",
			Handler:    _BankService_ChangeBalance_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _BankService_GetBalance_Handler,
		},
		{
			MethodName: "TransferMoney",
			Handler:    _BankService_TransferMoney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bank.proto",
}

func init() { proto.RegisterFile("proto/bank.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xc7, 0x49, 0x4c, 0x08, 0x39, 0x4e, 0x42, 0xee, 0x10, 0x90, 0x6f, 0xf8, 0xb8, 0xc8, 0xf7,
	0xde, 0x0a, 0xb1, 0x48, 0x24, 0xaa, 0x8a, 0x0a, 0x55, 0x55, 0x09, 0xb4, 0x15, 0x15, 0xb4, 0x95,
	0x69, 0xd5, 0xae, 0x8a, 0x06, 0x7b, 0x02, 0x23, 0x9c, 0xb1, 0xf1, 0x38, 0x48, 0x51, 0xd5, 0x4d,
	0x5f, 0xa1, 0x8f, 0xd6, 0x57, 0xe8, 0xb6, 0xeb, 0x6e, 0xab, 0xf9, 0x0a, 0x76, 0x08, 0x88, 0xb2,
	0xf3, 0x39, 0xc7, 0xe7, 0x77, 0xce, 0xff, 0x3f, 0x93, 0x18, 0x1a, 0x71, 0x12, 0xa5, 0x51, 0xe7,
	0x04, 0xb3, 0xf3, 0xb6, 0x7c, 0x44, 0x16, 0x8e, 0x69, 0x6b, 0xf9, 0x34, 0x8a, 0x4e, 0x43, 0xd2,
	0xc1, 0x31, 0xed, 0x60, 0xc6, 0xa2, 0x14, 0xa7, 0x34, 0x62, 0x5c, 0xbd, 0xe2, 0x7e, 0x84, 0x99,
	0xdd, 0x90, 0x12, 0x96, 0xa2, 0x3a, 0x14, 0x69, 0xe0, 0x14, 0xd6, 0x0a, 0xeb, 0x25, 0xaf, 0x48,
	0x03, 0x84, 0x60, 0x9a, 0xe1, 0x3e, 0x71, 0x8a, 0x6b, 0x85, 0xf5, 0x8a, 0x27, 0x9f, 0x51, 0x13,
	0x4a, 0xa4, 0x8f, 0x69, 0xe8, 0x58, 0x32, 0xa9, 0x02, 0x91, 0x8d, 0xcf, 0x22, 0x46, 0x9c, 0x69,
	0x95, 0x95, 0x81, 0xfb, 0x16, 0xca, 0x3b, 0xbe, 0x1f, 0x0d, 0x26, 0xa0, 0x97, 0xa0, 0xe2, 0xcb,
	0xa1, 0xc7, 0x34, 0x90, 0xfc, 0x92, 0x37, 0xab, 0x12, 0xfb, 0x01, 0x72, 0xa0, 0x7c, 0x82, 0x43,
	0xcc, 0x7c, 0x22, 0xa7, 0x58, 0x9e, 0x09, 0xdd, 0x9f, 0x05, 0xb0, 0xdf, 0x25, 0x98, 0x71, 0xec,
	0x0b, 0x09, 0xd7, 0xb0, 0x4f, 0x01, 0x02, 0xda, 0xeb, 0x1d, 0xf7, 0x23, 0x46, 0x86, 0x4e, 0x71,
	0xcd, 0x5a, 0xb7, 0x37, 0xff, 0x69, 0xe3, 0x98, 0xb6, 0x33, 0x5d, 0xed, 0x3d, 0xda, 0xeb, 0x1d,
	0x8a, 0x37, 0x9e, 0xb3, 0x34, 0x19, 0x7a, 0x95, 0xc0, 0xc4, 0x62, 0xb2, 0x1f, 0xf5, 0xfb, 0x84,
	0xa5, 0x5a, 0x9f, 0x09, 0x45, 0x85, 0x0f, 0x7c, 0x9f, 0x70, 0x2e, 0x35, 0xce, 0x7a, 0x26, 0x44,
	0xcb, 0x50, 0x49, 0x69, 0x9f, 0xf0, 0x14, 0xf7, 0x63, 0xa7, 0x24, 0xf7, 0xbd, 0x4a, 0xb4, 0x9e,
	0x40, 0x3d, 0x3f, 0x0e, 0x35, 0xc0, 0x3a, 0x27, 0x43, 0xbd, 0xb4, 0x78, 0x14, 0xee, 0x5d, 0xe2,
	0x70, 0xa0, 0x8c, 0xb6, 0x3c, 0x15, 0x6c, 0x17, 0x1f, 0x17, 0xdc, 0x15, 0xb0, 0x3d, 0x72, 0x31,
	0x20, 0x3c, 0xed, 0x0e, 0xf7, 0x83, 0x71, 0xb9, 0xee, 0x33, 0xa8, 0xeb, 0xb2, 0xf1, 0x79, 0x15,
	0xac, 0x84, 0x5c, 0xc8, 0x57, 0xec, 0xcd, 0xaa, 0x54, 0xae, 0x4b, 0x9e, 0x28, 0x68, 0x42, 0x71,
	0x44, 0x68, 0x43, 0x4d, 0x13, 0xf4, 0x1d, 0x58, 0xc9, 0x02, 0x6c, 0x09, 0x50, 0x15, 0xd9, 0xef,
	0x1e, 0xc1, 0x7c, 0x7e, 0xa2, 0xf2, 0xed, 0x01, 0x94, 0xb1, 0x8a, 0x27, 0x8e, 0x36, 0x45, 0xa1,
	0xd4, 0x1c, 0x8d, 0x54, 0x2a, 0x03, 0x37, 0x84, 0xa6, 0x86, 0xca, 0x53, 0xea, 0x91, 0x44, 0x51,
	0x57, 0xc1, 0xe2, 0x89, 0x3f, 0x59, 0x0c, 0x4f, 0x7c, 0x51, 0x0f, 0x78, 0x2a, 0x59, 0xd7, 0xea,
	0x01, 0xcf, 0x4c, 0xb3, 0xb2, 0xd3, 0xb6, 0x60, 0xce, 0x23, 0x3c, 0x8e, 0x18, 0x27, 0xc6, 0xb5,
	0xff, 0x60, 0x26, 0x21, 0x7c, 0x10, 0x8a, 0xed, 0xad, 0x6b, 0x2c, 0x5d, 0x73, 0x1f, 0x09, 0xb7,
	0x55, 0xa3, 0x36, 0xeb, 0xdf, 0xb1, 0xbe, 0x9c, 0x5f, 0xa6, 0xed, 0x7f, 0x61, 0xb1, 0x6a, 0x53,
	0xb2, 0x46, 0x6b, 0x15, 0x32, 0x6b, 0x6d, 0xfe, 0x2a, 0x83, 0xdd, 0xc5, 0xec, 0xfc, 0x88, 0x24,
	0x97, 0xd4, 0x27, 0xe8, 0x05, 0xd8, 0x07, 0xd4, 0x1c, 0x0b, 0x47, 0x0d, 0x89, 0xce, 0x5c, 0x86,
	0xd6, 0xbc, 0xce, 0x64, 0x37, 0x72, 0x1b, 0x5f, 0xbf, 0xff, 0xf8, 0x56, 0x04, 0x34, 0xdb, 0xf1,
	0x75, 0xe3, 0x2b, 0x00, 0x8f, 0xe0, 0x40, 0x6f, 0x7c, 0x47, 0xcc, 0x82, 0xc4, 0xcc, 0xa1, 0x9a,
	0xc1, 0x74, 0x3e, 0xd3, 0xe0, 0x0b, 0xfa, 0x04, 0x4d, 0xb1, 0x93, 0x36, 0x86, 0x77, 0x87, 0x37,
	0x52, 0x9b, 0x39, 0xaa, 0x6e, 0x70, 0x57, 0x25, 0xd6, 0x41, 0x8b, 0x39, 0x6c, 0x47, 0xdf, 0x0e,
	0x8e, 0x5e, 0x43, 0x75, 0x37, 0x21, 0x38, 0x35, 0xfe, 0xa2, 0x2c, 0x57, 0xe5, 0x6e, 0xdd, 0xd7,
	0x1d, 0xc9, 0xde, 0x96, 0xb7, 0xfd, 0x00, 0xaa, 0x7b, 0x24, 0x24, 0x23, 0xde, 0x9f, 0xa9, 0xdf,
	0x18, 0x53, 0xbf, 0x0f, 0xd5, 0xac, 0xfa, 0x3b, 0xab, 0xfe, 0x4b, 0xe2, 0x6c, 0x54, 0xb9, 0x12,
	0x7a, 0x28, 0x7e, 0xd7, 0x38, 0x30, 0xf7, 0xef, 0xae, 0xa4, 0x45, 0x49, 0x6a, 0xa0, 0xfa, 0x88,
	0xa4, 0x36, 0xf3, 0xa0, 0xa6, 0x7c, 0x33, 0xc0, 0xf9, 0x2c, 0x50, 0x27, 0x6f, 0x67, 0xba, 0x57,
	0xdb, 0x29, 0xef, 0x3e, 0x40, 0xed, 0x7d, 0x1c, 0xdc, 0x8f, 0xb9, 0x24, 0x99, 0x0b, 0xad, 0xb1,
	0x3d, 0x15, 0xf8, 0x0d, 0xd4, 0xd4, 0xa1, 0xdc, 0x53, 0xfd, 0xc6, 0xb8, 0xfa, 0x1d, 0xa8, 0xed,
	0x9e, 0x61, 0x76, 0x4a, 0xba, 0xea, 0x2b, 0x81, 0x9c, 0x09, 0x9b, 0xca, 0x9f, 0xde, 0x0d, 0xe0,
	0x29, 0xb4, 0x05, 0xf0, 0x92, 0xa4, 0xa6, 0x7f, 0xa2, 0x52, 0x94, 0x6b, 0x95, 0x38, 0x77, 0x0a,
	0x75, 0xa1, 0x96, 0xff, 0xcf, 0xfa, 0x3b, 0xdb, 0x9b, 0x2b, 0xdd, 0x34, 0xfc, 0x64, 0x46, 0x7e,
	0x87, 0x1f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x30, 0xa8, 0xd5, 0xbe, 0x07, 0x00, 0x00,
}
